spring:
  application:
    name: attendance-management
  
  datasource:
    url: ${DB_URL:jdbc:mysql://database-1.c9w4uoqc4q95.ap-south-1.rds.amazonaws.com:3306/attendance_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:bharathan}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: MySecureJWTSecretKeyForAttendanceManagementSystemWithAtLeast64CharactersLength!
  expiration: 86400000

logging:
  level:
    root: INFO
    com.edutech.attendance: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health
